project_id = "komqiadgeaapeuuzbovn"

[functions.public-register]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.issue-certificate]
verify_jwt = false